### ISSUE TITLE
Question: Wait for SCSS to Load

### ISSUE THREAD

**Issue by Ericky14** [wearepush/redux-starter#33]
### Question

Is there any way for the page to wait for the scss to load before the page is loaded? Right now the website loads with none of the project's scss and then after a little delay, it all loads.

**Comment by Iuriy-Budnikov** [comment]
Hey @Ericky14 ,

Are you testing in dev `npm run dev` or prod `npm run prod` mode?

**Comment by Ericky14** [comment]
```npm run dev```

**Comment by Iuriy-Budnikov** [comment]
@Ericky14 https://github.com/webpack/webpack/issues/1427
I think this is common problem. I'll try to resolve it.

Thanks

**Comment by Iuriy-Budnikov** [comment]
@Ericky14 resolved!
