### ISSUE TITLE
Deploying Prod Build

### ISSUE THREAD

**Issue by Ericky14** [wearepush/redux-starter#52]
Hello,

How do you get a build out of the project that you can just drop inside a server folder and have it run? I tried looking at the build commands on the package.json, but I am not exactly sure what they do and they don't generate an index.html.

**Comment by Iuriy-Budnikov** [comment]
Hey @Ericky14 ,

Current version can be run only with node server. 
But you can add webpack html plugin to generate static index.html

**Comment by Ericky14** [comment]
Thanks for the answer.

**Comment by Ericky14** [comment]
Sorry, I have one more question if possible @Iuriy-Budnikov 

To run the full app from a index.html, would I need to import both the server and client build scripts into it? Also, do I need to add anything extra to the index.html file?

**Comment by Iuriy-Budnikov** [comment]
> To run the full app from a index.html, would I need to import both the server and client build scripts into it
You will need only client side scripts. Rest of things can be removed.

> Also, do I need to add anything extra to the index.html file?
No.

**Comment by Iuriy-Budnikov** [comment]
@Ericky14 ,
I can create a separate task for generating html build.

**Comment by Iuriy-Budnikov** [comment]
Hey @Ericky14 ,

Here a branch with static generator:
https://github.com/wearepush/redux-starter/tree/chore/static

Command `prod:client:static:build` will generates an index.html in `static/assets`
