### ISSUE TITLE
Possible Bug: Using OrderedMap in redux module

### ISSUE THREAD

**Issue by bsadecki** [wearepush/redux-starter#57]
I'm using `OrderedMap` to wrap one of my redux module state properties. But I *think* it's getting converted to a standard Map when it is passed from server to client.

redux/modules/records.js
```
...
const initialState = {
  records: {}
}

const initialImmutableState = fromJS(initialState);

export default function reducer(state = initialImmutableState, action = {}) {
  switch (action.type) {
  ...
    case RECORDS_SUCCESS: {
      const { result } = action
      const teams = OrderedMap( // Returns a Map with a correctly casted integer key and preserves order
        result.get('results')
          .map(conversation => [conversation.get('id'), conversation])
      )
      return state.withMutations((mutableState) => {
        mutableState.set('teams', teams)
      })
    }
...
```

This works well for client-side activities and fetching information live. But when the action that calls the `RECORDS` types is called in `fetchData` I get this warning in the browser:

> warning.js:33 Warning: Prop `records` did not match. Server: "OrderedMap { 2: Map { ... }, 3: Map { ... } }" Client: "Map { \"2\": Map { ... }, \"3\": Map { ... } }"

I logged `store.getState()` when it is passed to `<Provider />` in createSSR.js and it's still correctly cast as an OrderedMap.

Is there something in this framework that unpacks the state immutables and re-casts them so that OrderedMap -> Map? Or is this a higher level `react-redux` issue?

**Comment by Iuriy-Budnikov** [comment]
Thanks @bsadecki , I'll check and back to you.

**Comment by Iuriy-Budnikov** [comment]
Hey @bsadecki ,
OrderedMap returns an object instead of array. Thats was an issue. 
You need to use sort func.

**Comment by Iuriy-Budnikov** [comment]
![screen shot 2017-12-22 at 11 08 14 am](https://user-images.githubusercontent.com/3968373/34292180-6d896dcc-e708-11e7-9b1c-7fd9348a900e.png)

**Comment by bsadecki** [comment]
Returning an object is expected. I want to keep an OrderedMap so I can easily update the records list on the fly.

For instance, if I'm in a list view displaying three items you posted above, I can delete one by calling the action `this.props.deleteRecord(2)` I can pass the `id` through as an action property:

```
export function deleteRecord(id) {
  return {
    types: [RECORD_DELETE, RECORD_DELETE_SUCCESS, RECORD_DELETE_FAIL],
    promise: client => new Promise((resolve, reject) => {
      client.delete(
        `/api/record/${conversationId}/`
      )
        .then(resolve)
        .catch(reject)
    }),
    id: id
  }
}
```

And then remove the item from the stored list in the action callback:

```
    case RECORD_DELETE_SUCCESS: {
      return state.withMutations((mutableState) => {
        mutableState
          .set('recordDeleteLoading', false)
          .set('recordDeleteError', undefined)
          .deleteIn(['records', action.id])
      })
    }
```

That way, I can keep the list view updated without refreshing it. And I don't have to do a `find` command to find the matching record to delete like I would with a List.

When I render the `records` list to view, I do need to convert it to a List or Array first or React complains. But that's pretty easy.


The issue is that something's happening in SSR that converts the `OrderedMap` to a `Map` after it's prefetched.

**Comment by Iuriy-Budnikov** [comment]
Hey @bsadecki ,
Yes bug in the JSON.stringify(store.getState()) [html.js](https://github.com/wearepush/redux-starter/blob/master/src/server/SSR/html.js#L13)
It looks like stringify keep origin order by key.

**Comment by Iuriy-Budnikov** [comment]
Hey @bsadecki ,
It looks like bug in the server render http://prntscr.com/hrbxzf

**Comment by Iuriy-Budnikov** [comment]
import { renderToString } from 'react-dom/server';

**Comment by Iuriy-Budnikov** [comment]
@bsadecki , records has wrong order at the server side http://prntscr.com/hrc262

**Comment by Iuriy-Budnikov** [comment]
https://github.com/zalmoxisus/redux-devtools-extension/issues/339

**Comment by Iuriy-Budnikov** [comment]
Also bug can be that immutable map object has OrderedMap object

**Comment by bsadecki** [comment]
With your guidance, I *think* I found some workarounds. At least, I'm no longer seeing a warning for server-client mismatch.

modules/records.js
```
const initialState = {
  ...
  records: {},
  ...
}
const initialImmutableState = fromJS(initialState).set('records', OrderedMap(initialState.records))
...
```

records list component:
```
{_.values(teams.toJS()).map(team => (
  ...
}
```

**Comment by Iuriy-Budnikov** [comment]
Try to avoid .toJS(). This is method to slow.
